
import Nav from "@/components/Nav.jsx";
import "./globals.css";
import {Poppins} from 'next/font/google'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const poppins = Poppins({subsets: ['letin'], weight: ['400', '700']})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Nav/>
      <div>hello</div>
      <body className={poppins.className}>
        {/* {children} */}
      </body>
    </html>
  );
}
